language: python
python:
    - 2.7
before_script:
	- sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
install:
    - pip install -e .[test]
script:
    nosetests --with-coverage --cover-package=hamlreloader
after_script:
    coveralls